# Generated by Django 3.2.4 on 2021-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorswatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('hex_value', models.CharField(max_length=10)),
                ('rgb_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
