# Generated by Django 3.2.4 on 2021-06-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorswatch', '0003_colorsmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorsmapping',
            old_name='shades',
            new_name='hex_value',
        ),
    ]
