# Generated by Django 3.2.4 on 2021-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorswatch', '0004_rename_shades_colorsmapping_hex_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=10)),
                ('color2', models.CharField(max_length=10)),
                ('color3', models.CharField(max_length=10)),
                ('color4', models.CharField(max_length=10)),
            ],
        ),
    ]
