# Generated by Django 3.2.4 on 2021-06-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorswatch', '0007_auto_20210623_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorSwatch',
        ),
    ]
