# Generated by Django 3.2.4 on 2021-06-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorswatch', '0010_auto_20210623_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorToHexCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
                ('hex_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorToHexMapping',
        ),
    ]
